<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SAP_TSC_ver_pedido_desblq_liberar</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2ac8589a-1740-4b6c-a5ef-bff546a8bc6d</testSuiteGuid>
   <testCaseLink>
      <guid>950a0287-41b1-4353-beae-a3956c96fc2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_SAP</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7891fafe-ba20-4e37-91b6-d0bb5db930cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_se16n_n_pedidos</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c108c028-be81-4e30-938f-5b86e0afa59e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DGScenarios</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>fda98028-a58f-4ac3-8d82-bf9b96d0bf4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b80351a-f1c1-4e75-9228-8c28426d602e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0912fdd8-15af-4b7c-8eab-0d8c672cedfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b7e60a5-6f70-45a1-a720-e474c0a884c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59be12e7-5ed3-4107-9496-5a347f0e3acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b67ab89e-6093-4c40-8b6d-73ef69f5126b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4a69a78-39f1-4e3f-9785-71f9c4f64afd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03e0cd81-694a-46de-b4e5-de2bc7b8e20b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4e607a4-9aed-4b53-bf31-94029036d566</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_z_sd_libera_pedido</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6616e812-1934-42ae-bad6-ee94a0b0ec45</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DGScenarios</testDataId>
      </testDataLink>
   </testCaseLink>
   <testCaseLink>
      <guid>050eedc4-5de9-46fb-8f0d-777fe00df1f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_vkm4</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>366f5536-a6db-4960-a6e1-4c8c9c26b551</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DGScenarios</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>366f5536-a6db-4960-a6e1-4c8c9c26b551</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>out_n_pedido_sap</value>
         <variableId>4e0a1ba6-6bc7-4132-bc49-3985d2f83d2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>258f9718-bba4-4074-b0ff-49b869a2e608</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_z_sd_punto_arranque</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>edace656-96fc-415a-9ebd-bb157968c725</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DGScenarios</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>edace656-96fc-415a-9ebd-bb157968c725</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>out_n_pedido_sap</value>
         <variableId>b3025694-e176-4994-9a58-e8bdcd9d3bea</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
