<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SAP_03_extraer_n_pedido_se16n</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>733120ff-bdf6-49af-aabf-ed7891fd37ae</testSuiteGuid>
   <testCaseLink>
      <guid>d28b90ba-e97e-4286-a9d6-6e583a2c7b3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_se16n</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d6c07138-3651-446b-b41c-2f0e81790f5f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DGScenarios</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d6c07138-3651-446b-b41c-2f0e81790f5f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>out_ref_externa</value>
         <variableId>fda98028-a58f-4ac3-8d82-bf9b96d0bf4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b80351a-f1c1-4e75-9228-8c28426d602e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
