<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>1_dg_se16n_pedido_oc</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>31265540-6b18-4479-84bc-777d08adca26</testSuiteGuid>
   <testCaseLink>
      <guid>0fdfef4d-8e9f-4213-a492-d3be39f5544a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DG_Creacion_Pedido</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6ac1ff00-badc-4586-bd05-34b81dd160fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_se16n_n_pedidos</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9e5e836b-fead-4c97-a877-56331fae4e24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_se16n_orden_compras</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f67156ef-db83-4f1e-ba3a-a96fab5112f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be685e04-0f3b-4a66-bb63-7b1071b6d327</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc3514c9-55ed-412a-8873-a409d14dffd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1a91c54-228c-43fb-b0f8-eee2617eb4dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b39395d-77ec-470c-815c-486949ffaefa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d590c9a8-334c-4ed8-a01e-7e3fdeeff4b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>027a2981-6b62-4801-8383-0bd77b6d88ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b37e70a-e071-4e5d-b2cb-bd561ee0318e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1301c52-6cfa-4721-b10c-12c6a1bb0bed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SAP_se37_emular_123</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
