<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddwn_Codigo_Destinacion</name>
   <tag></tag>
   <elementGuidId>8cdc31f7-c57e-42c6-a678-8b4bec2acfd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='codigoDestinoDrp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codigoDestinoDrp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codigoDestinoDrp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	DECLARACION DE CORRECCION DE INGRESO A DEPOSITO
	DESTINACION DE IMPORTACION SIMPLIFICADA
	DESTINACION DE IMPORTACION SIMPLIFICADA DAP
	EXPORTACION A CONSUMO
	EXPORTACION A CONSUMO C/DIT SIN TRANSFORMACION
	EXPORTACION A CONSUMO C/DIT CON TRANFORMACION
	EXPORT.A CONS.C/DIT INGRES. P/TRANSF.EGRESADO S/TRANSF.
	EXPORTACION A CONSUMO DE EXPORT. TEMP. C/TRANSFORMACION
	EXPORTACION A CONSUMO DE EXPORT.TEMPORAL S/TRANSFORM.
	EXPORTACION A CONSUMO DE MERCADERIA EN CONSIGNACION
	EXPORTACION A CONSUMO DE MERC. CON PRECIOS REVISABLES
	EXPORTACION A CONSUMO DE CONCENTRADO DE MINERALES
	EGRESO A CONS.EN TNC MERC.ORIG.AAE EGRE.MOSMO PRODUCTOR
	EGRESO AL TNC DE MERC ORIG AAE E IMP CUIT DISTINTO PROD
	EGRESO P/CONS.EN TNC MERC. DEL AAE NO ORIG. EN EL AREA
	REIMPOR.AL TNC MERC. EXPORT. DESDE TNC AL AAE
	EGRESO DEL AAE A CONS. EN EXT. C/TRANS. TERRES. POR TNC
	EXPORT.RANCHO COMBUSTIBLE DE BUQUE BANDERA EXTRANJERA
	EXPO RANCHO Y APROVISIONAMIENTO DE MEDIO DE TRANSPORTE
	EXPORTACION DE MERCADERIAS EN CONSIGNACION
	EXPORTACION DE MERCADERIAS CON PRECIOS REVISABLES
	EXPORTACION DE CONCENTRADO DE MINERALES
	EXPORTACION TEMPORARIA CON TRANSFORMACION
	EXPORTACION TEMPORARIA SIN TRANSFORMACION
	EGRESO TEMP DEL AAE AL EXT. C/TRANS. TERRES. POR TNC
	EXPORTACION REGIMEN SIMPLIFICADO DECRETO NRO.855/97
	IMPORTACION A CONSUMO SIN DOC. DE TRANSPORTE
	IMPORT.A CONSUMO MERCADERIA REGIMEN DE SOLICITUD PREVIA
	IMPORT. CONSUMO DE MERC. VIA TERREST. EN ENVIOS FRACC.
	IMPORTACION A CONSUMO CON DOCUMENTO DE TRANSPORTE
	IMPORTACION A CONSUMO C/DOC. DE TRANSPORTE D.A.P.
	IMPORTACION A CONSUMO SOBRE DEPOSITO DE ALMACENAMIENTO
	IMPORTACION A CONSUMO REGIMEN AUTOMOTRIZ C/DOC DAP
	IMPORTACION A CONSUMO ADUANA DOMICILIARIA C/DOC DAP
	RETORNO EXPORT.TEMP.C/TRANSFORMACION S/DOC.TRANSPORTE
	RETORNO EXPORT.TEMPOR.C/TRANSFORM.C/DOC. DE TRANSPORTE
	RETORNO EXPORT.TEMP.C/TRAFORM.C/DOC.TRANSPORTE D.A.P.
	RETORNO EXPORT.TEMP.C/TRANSF.S/ DEP.DE ALMACENAMIENTO
	RETORNO EXPOR.TEMP.S/TRANSFORMACION S/DOC.TRANSPORTE
	RETORNO EXPORT.TEMP.S/TRANSFORM.C/DOC.DE TRANSP.
	RETORNO EXPORT.TEMP.S/TRANSF.C/DOC.TRANSPORT.D.A.P.
	RETORNO EXPORT.TEMP.S/TRANSF.SOBRE DEP. ALMACENAMIENTO
	RETORNO DE EXPORTACION EN CONSIGNACION C/DOC.TRANSP.
	RETORNO DE EXPORT.EN CONSIGNACION C/DOC.TRANSP.DAP
	IMPORTACION A CONSUMO DE IMPORTACION TEMP.C/TRANSFOMAC.
	IMPORTACION A CONSUMO DE RESIDUOS DE IMPORT.TEMP.C/T
	IMPORTACION A CONSUMO DE IMP.TEMPORARIA S/TRANSFORMAR
	IMPORTACION SUSPENSIVA DE DEP. DE ALMACENAMIENTO
	DECLARAC. PARA EL FRACC. DE LOS BULTOS DE UN DOC. TRANP
	IMPORTACION A CONSUMO P/GRAN.OPERADORES S/DOC.TRANSP.
	IMPORT.CONSUMO GRANDES OPER.DE ENV.FRACC.P/VIA TERREST.
	IMPORTACION A CONSUMO P/GRAN.OPER.CON DOC.TRANSPORTE
	IMPORTACION A CONSUMO P/GRAN.OPER.C/DOC.DE TRANSP.DAP
	IMP.A CONSUMO P/GRAN.OPER.SOBRE DEP. DE ALMACENAMIENTO
	IMPORTACION A CONSUMO P/GRAN.OPER.CON AUT.PROVISORIA
	IMPORTACION TEMPORARIA S/TRANSFORM. S/DOC.TRANSPORTE
	IMPORT. TEMPORAL S/TRANSF. VIA TERREST. DE ENVIOS FRACC
	IMPORTACION TEMPORARIA S/TRANSFORMACION C/DOC.TRANSPORT
	IMPORTACION TEMPORARIA S/TRANSF. C/DOC. TRANSP. DAP
	IMPORTACION TEMPORARIA S/TRANSF. SOBRE DEP. ALMACENAM.
	IMPORTACION TEMPORAL REGIMEN AUTOMOTRIZ S/TRANSF.DAP
	IMPORTACION TEMPORARIA PARA TRANSFROM.S/DOC.TRANSPORTE
	IMPOR. TEMPORAL C/TRNSF. VIA TERREST. DE ENVIOS FRACC.
	IMPORTACION TEMPORARIA P/TRANSFORM.C/DOC.DE TRANSPORTE
	IMPORTACION TEMPORARIA P/TRANSF.C/DOC DE TRANSP.DAP
	IMPORTACION TEMPORARIA C/TRANSFORM. SOBRE DEP.ALMAC.
	IMPORTACION TEMPORAL REGIMEN AUTOMOTRIZ C/TRANSF.DAP
	LICENCIA AUTOMATICA PREVIA DE IMPORTACION
	LICENCIA NO AUTOMATICA DE CALZADO
	LICENCIA NO AUTOMATICA DE PAPEL
	REEMBARCO SIN DOCUMENTO DE TRANSPORTE
	REEMBARCO CON DOCUMENTO DE TRANSPORTE
	REEMBARCO CON DOCUMENTO DE TRANSPORTE DAP
	REEMBARCO SOBRE DESTINACION SUSP. DE ALMACENAMIENTO
	EXPORTACION POR REMOVIDO VIA ACUATICA Y TERRESTRE
	REZAGO DE MERC.DE DESTINACION SUSP.DE ALMACENAMIENTO
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRANSF.E/US.DIR.Y/O INDIR.C/REENVASADO O REENVASADO USU
	TRASBORDO CON DOCUMENTO DE TRANSPORTE
	TRASBORDO CON DOCUMENTO DE TRANSPORTE DAP
	IMP.TEMP.GRAN.OPER.CON DOC.DE TRANS.SIN TRANSFORMACION
	IMPORTACION TEMP.GRAN.OPERADOR S/TRANS.C/DOC.TRANSP.DAP
	IMP.TEMP.S/TRANSF.P/GRAN.OPER.SOBRE DEP.ALMACENAMIENTO
	IMPORTACION TEMPORAL GRANDES OPERADORES S/TRANSF.DAP
	IMPORTACION TEMP.GRAN.OPER.P/TRANS.CON DOC.TRANSPORTE
	IMPORT.TEMPORARIA GRAN.OPERADORES P/TRANS.C/DOC.DAP
	IMP.TEMP.C/TRANSF.P/GRAN.OPER.SOBRE DEP.ALMACENAMIENTO.
	IMPORTACION TEMPORAL GRANDES OPERADORES C/TRANSF.DAP
	TRASLADO DETALLADO CON DOCUMENTO DE TRANSPORTE
	TRASLADO DETALLADO CON DOCUMENTO DE TRANSPORTE DAP
	TRASLADO DET. CON DOC. TRANSP. A MAS DE UN DEP FISCAL
	TRANSITO DE IMPORTACION SIN DOCUMENTO DE TRANSPORTE
	TRANSITO DE IMPORTACION CON DOCUMENTO DE TRANSPORTE
	TRANSITO DE IMPORTACION CON DOCUMENTO DE TRANSPORTE DAP
	TRANSITO DE IMPORTACION S/DEPOSITO DE ALMACENAMIENTO
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	TRANSFERENCIA ENTRE USUARIOS DIRECTOS Y/O INDIRECTOS
	EGRESO ZF PARA CONSUMO EN EL TERRITORIO
	EG.POR AEROP./PUERTO DE LA ZF EN EL MISMO ESTADO AL EXT
	EGR.ZF DE UN PRODUCTO DE UN PROCESO PRODUCTIVO AL T.A.
	EGR ZF DE UN PROD.DE PROC.PRODUCT. O REPARACION AL EXT
	EGR.ZF RESIDUO DE UN PROCESO PRODUCT.C/VALOR COM.AL T.A
	EGR ZF DE UN RESIDUO DE PROCESO PROD.C/VALOR COM AL EXT
	RETORNO AL T.A. DE ACUERDO AL ART.566 DEL C.A.
	RETORNO AL T.A. DE MERCADERIA EXPORTADA TEMPORALMENTE
	INGR.ZF DE BIENES DE CAP.LIBRE CIRC.P/RADIC.DEFIN.DE TA
	ING.ZF VITUALLAS Y MERC.DEST.CONTRUCC.INSTAL. DEL EXTER
	INGR.ZF BIENES DE CAPITAL PARA RADIC.DEFINITIVA DEL EXT
	INGR.ZF MERC.LIBRE CIRC.P/ALMAC./COMERC./REP. DEL T.A.
	ING.ZF MERC.ALMACENAM.Y/O COMERC. Y/O REPARAC. DEL EXT.
	ING.ZF INSUM.LIBRE CIRC.EN FORMA TEMP P/PROC.PROD.DE TA
	ING.ZF INSUMOS LIBRE CIRC.P/PROC.PRODUCT. DESDE T.A.
	ING.ZF INSUMOS PARA PROCESOS PRODUCTIVOS DEL EXTERIOR
	REEMBARCO POR AEROPUERTO/PUERTO DE LA Z.F. MISMO ESTADO
	EG.Z.F.TRANSITO AL EXTERIOR EN EL MISMO ESTADO DE ING.

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codigoDestinoDrp&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='codigoDestinoDrp']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table/tbody/tr[12]/td/table/tbody/tr[14]/td[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cod.de destinación'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código de aduana'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de despacho'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dig.Verif.Nr.Despach'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
