<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>container_Procesar_liquidaciones</name>
   <tag></tag>
   <elementGuidId>2bceb52a-9223-42e8-a7c5-e370b44546ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='webguiPopupWindow1-cntTD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>webguiPopupWindow1-cntTD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>urPWContentTableCell</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Si No&lt;div id=&quot;mnu_20732-container&quot; class=&quot;urMnu lsPOMNContainer lsPopupMenu__metaData&quot; style=&quot;display:inline-block;&quot;>&lt;div id=&quot;mnu_20732-scrlup&quot; class=&quot;urMnuScr urMnuScrUp&quot; style=&quot;display:none;&quot;>&lt;img width=&quot;1px&quot; src=&quot;/sap/public/icmandir/its/1x1.gif&quot;/>&lt;/div>&lt;div id=&quot;mnu_20732-cnt&quot; class=&quot;lsMnuCnt&quot; style=&quot;width:100%;overflow:hidden;&quot;>&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; id=&quot;mnu_20732&quot; ct=&quot;POMN&quot; lsdata=&quot;{6:{SID:'wnd[1]/mpop',Type:'GuiMenu'}}&quot; lsevents=&quot;{Select:[{ClientAction:'none'},{modalNo:'1',rgv:[{code:'action/4',submit:true,type:'GuiMenu'}]}]}&quot; class=&quot;lsMnuTable&quot; style=&quot;width:100%;&quot;>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;tbody>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot;{1:'Ayuda',15:'F1',18:{SID:'wnd[1]/mpop/menu[0]',Type:'GuiMenu',VKey:'1'}}&quot; id=&quot;wnd[1]/mpop/menu[0]&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span style=&quot;white-space:nowrap;&quot;>Ayuda&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; style=&quot;white-space:nowrap;&quot;>&amp;nbsp;(F1)&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot;{1:'Entradas\x20posibles',15:'F4',18:{SID:'wnd[1]/mpop/menu[1]',Type:'GuiMenu',VKey:'4'}}&quot; id=&quot;wnd[1]/mpop/menu[1]&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span style=&quot;white-space:nowrap;&quot;>Entradas posibles&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; style=&quot;white-space:nowrap;&quot;>&amp;nbsp;(F4)&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;/tbody>&lt;/table>&lt;/div>&lt;div id=&quot;mnu_20732-scrldwn&quot; class=&quot;urMnuScr urMnuScrDwn&quot; style=&quot;display:none;&quot;>&lt;img width=&quot;1px&quot; src=&quot;/sap/public/icmandir/its/1x1.gif&quot;/>&lt;/div>&lt;div id=&quot;mnu_20732-pointer&quot; class=&quot;lsQVPointer&quot;>&lt;/div>&lt;/div></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webguiPopupWindow1-cntTD&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SAP/Prueba_pami_nc/iframe_SAPNetWeaver740IntegratedITSWebAS(Kernel749_RELPatch800)_URLSPW-0</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='webguiPopupWindow1-cntTD']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='webguiPopupWindow1-cnttbl']/tbody/tr/td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procesar / reversar liquidaciones'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td</value>
   </webElementXpaths>
</WebElementEntity>
